server:
  port: 8802

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启当前项目服务注册与发现
          lower-case-service-id: true #转小写
      routes:
        - id: 01
          uri: lb://eureka-client
          predicates:
            - Path=/person/**
            #- Query=token, abc.



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

